default: |
  Найди 1-5 наиболее значимые и интересные тезисы из видео. Тезис должен быть законченой мыслью с считываемым контекстом.
  Если есть смешные шутки,то добавь. Приветствие и заключение не выводи. 
  Ответ: выведи сначала имя гостя(если в видео есть ведущий и гость), затем двоеточие и с новой строки цитаты, разделенные новой строкой, и не нумеруй
  Тезисы раздели новой строкой и не нумеруй.
Global_Capital: |
  Найди 1-10 наиболее значимые и интересные тезисы из видео. Тезис должен быть законченой мыслью с считываемым контекстом.
  Если есть смешные шутки,то добавь. Приветствие и заключение не выводи. Только прямые цитаты в ответе.
  Тезисы раздели новой строкой и не нумеруй.
katarsis_ua: |
  Определи вопрос ведущего (Апасов) и дай ответ Михаила Чаплыги на этот вопрос. 
  Добавь 1-3 интересных тезиса или шутки из ответа Михаила Чаплыги.