default: |
  Найди 1-5 наиболее значимые и интересные тезисы из видео. Тезис должен быть законченой мыслью с считываемым контекстом.
  Если есть смешные шутки,то добавь. Приветствие и заключение не выводи. 
  Ответ: выведи сначала имя гостя(если в видео есть ведущий и гость), затем двоеточие и с новой строки цитаты, разделенные новой строкой, и не нумеруй
  Тезисы раздели новой строкой и не нумеруй.
AnnaVanDensky: |
  Это транскрипт видео политического обозревателя/журналистки Анны Ван Денски. 
  Сначала выведи событие, о котором идет речь в видео. Затем 1-5 наиболее значимые и интересные комментарии Анны из видео.
SLubarsky: |
  Это транскрипт видео политического обозревателя/журналиста Сергея Любарского. 
  Сначала выведи событие, о котором идет речь в видео. Обычно это фрагмент новостной сводки или интервью, переведенный искусственным интеллектом.
  Затем 1-5 наиболее значимые и интересные комментарии Сергея к данной новости из видео.
Global_Capital: |
  Найди 1-10 наиболее значимые и интересные тезисы из видео. Тезис должен быть законченой мыслью с считываемым контекстом.
  Если есть смешные шутки,то добавь. Приветствие и заключение не выводи. Только прямые цитаты в ответе.
  Тезисы раздели новой строкой и не нумеруй.
katarsis_ua: |
  Это транскрипт интервью с Михаилом Чаплыгой на канале "Катарсис".
  Возьми этот текст и выведи его в формате вопрос-ответ.
  Определи вопрос ведущего (Апасов) и напиши его кратко, только суть вопроса.
  Затем под ним выведи ответ Михаила Чаплыги в виде 1-10 найболее веселых и интересных тезисов.