AnnaVanDensky: |
  Найди 1-5 наиболее значимые тезисы сказанные в видео. 
  Только самые существенные прямые цитаты типа: 
  У Европы нет плана завершения войны; Зеленский марионетка британцев. 
  Тезисы раздели новой строкой и не нумеруй
SLubarsky: |
  Найди 1-5 наиболее значимые темы сказанные в видео. 
  Только самые существенные прямые цитаты типа: 
  У Европы нет плана завершения войны; Зеленский марионетка британцев. 
  Тезисы раздели новой строкой и не нумеруй
LEHIST_UA: |
  Найди 1-5 наиболее значимые тезисы в видео.  
  Только самые существенные прямые цитаты типа: 
  У Европы нет плана завершения войны; Зеленский марионетка британцев. 
  Тезисы раздели новой строкой и не нумеруй
PolitekaOnline: |
  Найди 1-5 наиболее значимые и интересные тезисы из видео. Только прямые цитаты точно и самые существенные и самые интересные.
  Ответ выведи сначала имя гостя(если есть), затем двоеточие и с новой строки затем цитаты, разделенные новой строкой, и не нумеруй
Global_Capital: |
  Найди наиболее значимые и существенные тезисы. Только прямые цитаты в ответе.
  Тезисы раздели новой строкой и не нумеруй.
HUGSFUND: |
  Найди наиболее значимые и существенные тезисы. Только прямые цитаты в ответе.
  Тезисы раздели новой строкой и не нумеруй.
katarsis_ua: |
  Найди самые значимые тезисы сказанные в видео Михаилом Чаплыгой. Ту мысль, которую он считает самой важной. И самую смешную шутку, если она была.
  Только прямые цитаты в ответе.
  Тезисы раздели новой строкой и не нумеруй.
nemyrialive: |
  Найди 1-5 наиболее значимые и интересные тезисы из видео. Только прямые цитаты точно и самые существенные и самые интересные.
  Ответ выведи сначала имя гостя(если есть), затем двоеточие и с новой строки затем цитаты, разделенные новой строкой, и не нумеруй
YuriyRomanenko_Ukraine: |
  Найди 1-5 наиболее значимые и интересные тезисы из видео. Только прямые цитаты точно и самые существенные и самые интересные.
  Ответ выведи сначала имя гостя(если есть), затем двоеточие и с новой строки затем цитаты, разделенные новой строкой, и не нумеруй
Dikiylive: |
  Найди 1-5 наиболее значимые и интересные тезисы из видео. Только прямые цитаты точно и самые существенные и самые интересные.
  Ответ выведи сначала имя гостя(если есть), затем двоеточие и с новой строки затем цитаты, разделенные новой строкой, и не нумеруй
vvlashchenko: |
  Найди 1-5 наиболее значимые и интересные тезисы из видео. Только прямые цитаты точно и самые существенные и самые интересные.
  Ответ выведи сначала имя гостя(если есть), затем двоеточие и с новой строки затем цитаты, разделенные новой строкой, и не нумеруй
OlegZhdanov: |
  Найди 1-5 наиболее значимые и существенные тезисы. Только прямые цитаты в ответе.
  Тезисы раздели новой строкой и не нумеруй.
AlexGoncharenko: |
  Найди 1-5 наиболее значимые и существенные тезисы. Только прямые цитаты в ответе.
  Тезисы раздели новой строкой и не нумеруй.